/**
 * Centralized Error Codes
 * All error codes used throughout the application
 * These are i18n keys that will be translated by the error handler
 */

// Authentication & Authorization
export const AUTH = {
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  ACCOUNT_DISABLED: 'ACCOUNT_DISABLED',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  INVALID_PASSWORD: 'INVALID_PASSWORD',
  PASSWORD_MISMATCH: 'PASSWORD_MISMATCH',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  TWO_FACTOR_REQUIRED: 'TWO_FACTOR_REQUIRED',
  INVALID_TWO_FACTOR_CODE: 'INVALID_TWO_FACTOR_CODE',
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  SESSION_EXPIRED: 'SESSION_EXPIRED'
}

// Validation
export const VALIDATION = {
  REQUIRED: 'REQUIRED',
  INVALID_FORMAT: 'INVALID_FORMAT',
  INVALID_EMAIL: 'EMAIL_INVALID',
  INVALID_PHONE: 'PHONE_INVALID_FORMAT',
  INVALID_DATE: 'INVALID_DATE',
  INVALID_ID: 'INVALID_ID',
  TOO_SHORT: 'TOO_SHORT',
  TOO_LONG: 'TOO_LONG',
  OUT_OF_RANGE: 'OUT_OF_RANGE'
}

// Resource Operations
export const RESOURCE = {
  NOT_FOUND: 'NOT_FOUND',
  ALREADY_EXISTS: 'ALREADY_EXISTS',
  DUPLICATE: 'DUPLICATE',
  CONFLICT: 'CONFLICT',
  IN_USE: 'IN_USE',
  CANNOT_DELETE: 'CANNOT_DELETE'
}

// Partner & Hotel
export const PARTNER = {
  REQUIRED: 'PARTNER_REQUIRED',
  NOT_FOUND: 'PARTNER_NOT_FOUND',
  INVALID: 'PARTNER_INVALID'
}

export const HOTEL = {
  NOT_FOUND: 'HOTEL_NOT_FOUND',
  INVALID_STATUS: 'INVALID_STATUS',
  BASE_NOT_FOUND: 'BASE_HOTEL_NOT_FOUND'
}

// Booking
export const BOOKING = {
  NOT_FOUND: 'BOOKING_NOT_FOUND',
  ALREADY_CANCELLED: 'BOOKING_ALREADY_CANCELLED',
  CANNOT_CANCEL: 'BOOKING_CANNOT_CANCEL',
  INVALID_STATUS: 'BOOKING_INVALID_STATUS',
  INVALID_DATES: 'BOOKING_INVALID_DATES',
  ROOM_NOT_AVAILABLE: 'ROOM_NOT_AVAILABLE',
  PRICE_CHANGED: 'PRICE_CHANGED'
}

// Files & Uploads
export const FILE = {
  REQUIRED: 'FILE_REQUIRED',
  TOO_LARGE: 'FILE_TOO_LARGE',
  INVALID_TYPE: 'FILE_INVALID_TYPE',
  UPLOAD_FAILED: 'FILE_UPLOAD_FAILED',
  NOT_FOUND: 'FILE_NOT_FOUND'
}

// Room & Room Type
export const ROOM = {
  NOT_FOUND: 'ROOM_NOT_FOUND',
  TYPE_NOT_FOUND: 'ROOM_TYPE_NOT_FOUND',
  TEMPLATE_NOT_FOUND: 'ROOM_TEMPLATE_NOT_FOUND',
  TEMPLATE_CODE_REQUIRED: 'ROOM_TEMPLATE_CODE_REQUIRED',
  TEMPLATE_CODE_EXISTS: 'ROOM_TEMPLATE_CODE_EXISTS'
}

// Pricing & Payment
export const PRICING = {
  NOT_FOUND: 'PRICING_NOT_FOUND',
  INVALID_AMOUNT: 'INVALID_AMOUNT',
  CURRENCY_REQUIRED: 'CURRENCY_REQUIRED',
  CURRENCY_INVALID: 'CURRENCY_INVALID'
}

// Server Errors
export const SERVER = {
  INTERNAL_ERROR: 'INTERNAL_SERVER_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  DATABASE_ERROR: 'DATABASE_ERROR'
}

// Create helper for checking if a string is an error code
export const isErrorCode = code => {
  const allCodes = [
    ...Object.values(AUTH),
    ...Object.values(VALIDATION),
    ...Object.values(RESOURCE),
    ...Object.values(PARTNER),
    ...Object.values(HOTEL),
    ...Object.values(BOOKING),
    ...Object.values(FILE),
    ...Object.values(ROOM),
    ...Object.values(PRICING),
    ...Object.values(SERVER)
  ]
  return allCodes.includes(code)
}

export default {
  AUTH,
  VALIDATION,
  RESOURCE,
  PARTNER,
  HOTEL,
  BOOKING,
  FILE,
  ROOM,
  PRICING,
  SERVER,
  isErrorCode
}
